[features]
seeds = false
skip-lint = false
[programs.devnet ]
farming = "5d9tLof4jXidE1eMaSu4go4QUKn53uJUuSNACnUUYgUp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/arhamsoft/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
